# Generated by Django 5.1.5 on 2025-01-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_useractivation_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivation',
        ),
    ]
